---
- hosts: localhost
  connection: local
  tasks:
    - name: Start the container
      docker_container:
        name: python-app
        image: itamarc/python-app:{{DOCKER_TAG}}
        state: started
        volumes:
          - /home/cloud_user/Documents/data:/WORK_REPO/data
